import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AOSInit } from './aos'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mars Portfolio',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <AOSInit />
      <body className={inter.className}  style={{ fontFamily: 'Poppins, sans-serif' }}>{children}</body>
    </html>
  )
}
